# Generated by Django 4.1.3 on 2022-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daftarpasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Keluhan', models.CharField(max_length=100)),
                ('Antrian', models.CharField(max_length=30)),
                ('Dokter', models.CharField(max_length=30)),
            ],
        ),
    ]
