# Generated by Django 4.1.3 on 2022-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Keluhan', models.CharField(max_length=300)),
                ('Antrian', models.IntegerField()),
                ('Dokter', models.CharField(max_length=30)),
            ],
        ),
    ]
